apiVersion: v1
kind: Service
metadata:
  name: conda-store-server
spec:
#  type: NodePort
  ports:
    - name: "8080"
#      nodePort: 30500
      port: 8080
      targetPort: 8080
  selector:
    app: conda-store-server
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: conda-store-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conda-store-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conda-store-server
  template:
    metadata:
      labels:
        app: conda-store-server
    spec:
      containers:
        - name: conda-store-server
          image: quansight/conda-store-server:2024.6.1
          args:
            - "conda-store-server"
            - "--config"
            - "/etc/conda-store/conda_store_config.py"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: "/etc/conda-store/"
              readOnly: true
#            - name: conda-store-storage
#              mountPath: "/opt/conda-store/conda-store/"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
              ephemeral-storage: "10Gi"
            requests:
              cpu: "1"
              memory: 1Gi
              ephemeral-storage: "10Gi"
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: conda-store-config
#        - name: conda-store-storage
#          persistentVolumeClaim:
#            claimName: conda-store-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conda-store-ingress
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy.org/allow-origin: http://localhost:8000
    haproxy.org/allow-credentials: "true"
    haproxy.org/allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    haproxy.org/allow-headers: "Content-Type"
spec:
  rules:
  - host: conda-store-ndp.nrp-nautilus.io
    http:
      paths:
        - backend:
            service:
              name: conda-store-server
              port:
                number: 8080
          path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - conda-store-ndp.nrp-nautilus.io
