apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: conda-store-worker-claim
  name: conda-store-worker-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conda-store-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conda-store-worker
  template:
    metadata:
      labels:
        app: conda-store-worker
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: [ 'sh', '-c', 'chown -R 1000:1000 /opt/conda-store/']
          volumeMounts:
            - name: storage
              mountPath: "/opt/conda-store/"
      containers:
        - name: conda-store-server
          image: quansight/conda-store-server:2024.6.1
          args:
            - "conda-store-worker"
            - "--config"
            - "/etc/conda-store/conda_store_config.py"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: "/etc/conda-store/"
              readOnly: true
            - name: storage
              mountPath: "/opt/conda-store/"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: conda-store-config
        - name: storage
          persistentVolumeClaim:
            claimName: conda-store-worker-claim
