apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: [ 'sh', '-c', 'chown -R 1000:1000 /bitnami/redis/data' ]
          volumeMounts:
            - mountPath: /bitnami/redis/data
              name: redis-claim
      containers:
        - name: redis
          image: bitnami/redis:6.0.16
          env:
            - name: REDIS_PASSWORD
              value: password
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /bitnami/redis/data
              name: redis-claim
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
          securityContext:
            runAsUser: 1000  # Ensure this user has the right permissions
#            fsGroup: 1000    # Ensure the group has the right permissions
      restartPolicy: Always
      volumes:
        - name: redis-claim
          persistentVolumeClaim:
            claimName: redis-claim
